---
name: PyTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  POSTGRES_DB: rmdb

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Configure environment
      run: |
        git config --global user.name "repromon-test"
        git config --global user.email "repromon-test@example.com"
        uname -a

    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Create venv and poetry build
      run: |
        pwd
        ls -l
        venv/bin/pip install poetry
        venv/bin/poetry config virtualenvs.create false
        venv/bin/poetry config virtualenvs.in-project true 
        venv/bin/poetry env use `which python`
        venv/bin/python --version
        venv/bin/poetry --version
        venv/bin/poetry install
        venv/bin/poetry build
      shell: bash

    - name: Setup test DB
      run: |
        > db/db_dev.sqlite3
        venv/bin/poetry run setup_db
      shell: bash

    - name: Run pytest
      run: |
        venv/bin/poetry run pytest
      shell: bash
